server:
  port: 9527

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.tyw.springcloud.entities    # 所有Entity别名类所在包
  mapperLocations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-zuul-geteway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: gateway-9527
  company.name: www.tyw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept #用“*”全部禁用
  prefix: /tyw

